apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    component: docs
    {{- include "codeanywhere.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.components.docs.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    component: docs
