{{- if .Values.rabbitmq.enabled }}
{{- $rabbitMqErlangCookie := (randAlpha 20) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "messagebus-erlang-cookie") }}
{{- if $secret }}
{{- $rabbitMqErlangCookie = index $secret.data "rabbitmq-erlang-cookie" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: messagebus-erlang-cookie
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    {{- include "codeanywhere.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-erlang-cookie: {{ $rabbitMqErlangCookie }}
{{- end }}