apiVersion: v1
kind: Service
metadata:
  name: realtime-server
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    component: realtime-server
    {{- include "codeanywhere.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.components.realtimeServer.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    component: realtime-server
