{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-provisioner
  {{- if .Values.components.workspaceProvisioner.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.components.workspaceProvisioner.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    component: workspace-provisioner
    {{- include "codeanywhere.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
