apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.components.workspaceVolumeInit.serviceAccountName }}
  namespace: {{ .Values.components.workspaceVolumeInit.namespace }}
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    component: {{ .Values.components.workspaceVolumeInit.name }}
    {{- include "codeanywhere.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}