{{- if .Values.configuration.singleClusterDeployment }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "codeanywhere.workspaceNamespace" . }}
  labels:
    {{- include "codeanywhere.labels" . | nindent 4 }}
{{- end }}