{{- if .Values.configuration.singleClusterDeployment }}
{{- $cm := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspace-ssh-gateway
spec:
  secretName: workspace-ssh-gateway
  subject:
    organizations:
      - Codeanywhere
  isCA: false
  commonName: ssh-bastion-host-key
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $cm.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{- end }}