apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workspace-provisioner
  namespace: {{ include "codeanywhere.workspaceNamespace" . }}
  labels:
    app: {{ include "codeanywhere.fullname" . }}
    {{- include "codeanywhere.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "services/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["list", "watch", "get", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/status", "deployments/scale"]
  verbs: ["get", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["list", "get", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumeclaims/status"]
  verbs: ["list", "get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workspace-provisioner
  namespace: {{ include "codeanywhere.workspaceNamespace" . }}
subjects:
- kind: ServiceAccount
  name: workspace-provisioner
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: workspace-provisioner
  apiGroup: rbac.authorization.k8s.io
  
