apiVersion: batch/v1
kind: Job
metadata:
  name: "workspace-volume-init-job-{{ .Values.image.tag | default .Chart.AppVersion }}"
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: workspace-volume-init
        image: "{{ .Values.image.repository }}/{{ .Values.components.workspaceVolumeInit.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WORKSPACE_CLASS_NAME
          value: {{ .Values.configuration.defaultWorkspaceClassName | quote }}
        - name: PULL_IMAGES
          value: {{ .Values.components.workspaceVolumeInit.pullImages | quote }}
        - name: NAMESPACE
          value: {{ .Values.components.workspaceVolumeInit.namespace | quote }}
        - name: RESOURCE_TAG
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
      serviceAccountName: {{ .Values.components.workspaceVolumeInit.serviceAccountName }}
      restartPolicy: OnFailure
  backoffLimit: 4